import "server-only";

import { createHash } from "crypto";
import { and, eq, isNull, lt } from "drizzle-orm";

import { db } from "@/db";
import { authSessions } from "@/db/schema";
import { REFRESH_TOKEN_TTL_SECONDS } from "@/features/auth/constants";

/**
 * Refresh-session persistence — the revocation & rotation backbone.
 * Passwords use bcrypt (expensive, low-entropy secrets); refresh tokens use
 * SHA-256 (cheap, high-entropy opaque tokens) — the right hash per threat.
 */

export const hashRefreshToken = (token: string) =>
  createHash("sha256").update(token).digest("hex");

type SessionMetadata = {
  userAgent?: string | null;
  ipAddress?: string | null;
};

export async function createAuthSession(
  sessionId: string,
  identity: { userId: string } | { customerId: string },
  refreshToken: string,
  metadata: SessionMetadata = {},
) {
  // The session id is generated by the caller so it can be embedded as the
  // `sid` claim inside the refresh JWT it signs — token and row stay bound.
  const [row] = await db
    .insert(authSessions)
    .values({
      id: sessionId,
      ...identity,
      refreshTokenHash: hashRefreshToken(refreshToken),
      userAgent: metadata.userAgent ?? null,
      ipAddress: metadata.ipAddress ?? null,
      expiresAt: new Date(Date.now() + REFRESH_TOKEN_TTL_SECONDS * 1000),
      lastUsedAt: new Date(),
    })
    .returning();

  return row;
}

export type StoredSession = typeof authSessions.$inferSelect;

/** Returns the live (unrevoked, unexpired) session row, or null. */
export async function findLiveSession(sessionId: string): Promise<StoredSession | null> {
  const [row] = await db
    .select()
    .from(authSessions)
    .where(and(eq(authSessions.id, sessionId), isNull(authSessions.revokedAt)))
    .limit(1);

  if (!row || row.expiresAt < new Date()) return null;
  return row;
}

export async function revokeSession(sessionId: string) {
  await db
    .update(authSessions)
    .set({ revokedAt: new Date() })
    .where(and(eq(authSessions.id, sessionId), isNull(authSessions.revokedAt)));
}

export async function touchSession(sessionId: string) {
  await db
    .update(authSessions)
    .set({ lastUsedAt: new Date() })
    .where(eq(authSessions.id, sessionId));
}

/** Periodic hygiene: hard-drop long-dead sessions (cheap sweeps). */
export async function purgeExpiredSessions(before = new Date()) {
  await db.delete(authSessions).where(lt(authSessions.expiresAt, before));
}
